/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entrynom;
  GtkWidget *labelnom;
  GtkWidget *buttonHello;
  GtkWidget *labelHello;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed1), entrynom, 104, 32);
  gtk_widget_set_size_request (entrynom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  labelnom = gtk_label_new (_("Votre Nom"));
  gtk_widget_show (labelnom);
  gtk_fixed_put (GTK_FIXED (fixed1), labelnom, 24, 32);
  gtk_widget_set_size_request (labelnom, 73, 29);

  buttonHello = gtk_button_new_with_mnemonic (_("Say Hello"));
  gtk_widget_show (buttonHello);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonHello, 136, 104);
  gtk_widget_set_size_request (buttonHello, 74, 40);

  labelHello = gtk_label_new (_("HELLO!"));
  gtk_widget_show (labelHello);
  gtk_fixed_put (GTK_FIXED (fixed1), labelHello, 120, 192);
  gtk_widget_set_size_request (labelHello, 79, 76);

  g_signal_connect ((gpointer) buttonHello, "clicked",
                    G_CALLBACK (on_buttonHello_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (window1, labelnom, "labelnom");
  GLADE_HOOKUP_OBJECT (window1, buttonHello, "buttonHello");
  GLADE_HOOKUP_OBJECT (window1, labelHello, "labelHello");

  return window1;
}

