/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_faresfrini_ajoututilisateur_window (void);
GtkWidget* create_faresfrini_confirmerajout_window (void);
GtkWidget* create_faresfrini_confirmermodif_window (void);
GtkWidget* create_faresfrini_confirmersupp_window (void);
GtkWidget* create_faresfrini_modif_window (void);
GtkWidget* create_faresfrini_gestionutilisateur_window (void);
