/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *faresfrini_ajoututilisateur_window;
  GtkWidget *faresfrini_confirmerajout_window;
  GtkWidget *faresfrini_confirmermodif_window;
  GtkWidget *faresfrini_confirmersupp_window;
  GtkWidget *faresfrini_modif_window;
  GtkWidget *faresfrini_gestionutilisateur_window;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  faresfrini_ajoututilisateur_window = create_faresfrini_ajoututilisateur_window ();
  gtk_widget_show (faresfrini_ajoututilisateur_window);
  faresfrini_confirmerajout_window = create_faresfrini_confirmerajout_window ();
  gtk_widget_show (faresfrini_confirmerajout_window);
  faresfrini_confirmermodif_window = create_faresfrini_confirmermodif_window ();
  gtk_widget_show (faresfrini_confirmermodif_window);
  faresfrini_confirmersupp_window = create_faresfrini_confirmersupp_window ();
  gtk_widget_show (faresfrini_confirmersupp_window);
  faresfrini_modif_window = create_faresfrini_modif_window ();
  gtk_widget_show (faresfrini_modif_window);
  faresfrini_gestionutilisateur_window = create_faresfrini_gestionutilisateur_window ();
  gtk_widget_show (faresfrini_gestionutilisateur_window);

  gtk_main ();
  return 0;
}

