/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Affichage (void);
GtkWidget* create_authentification (void);
GtkWidget* create_ajouter (void);
GtkWidget* create_confirmer (void);
GtkWidget* create_resultat (void);
GtkWidget* create_modifier (void);
