/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_register_window (void)
{
  GtkWidget *register_window;
  GtkWidget *fixed1;
  GtkObject *day_spin_adj;
  GtkWidget *day_spin;
  GtkObject *month_spin_adj;
  GtkWidget *month_spin;
  GtkObject *year_spin_adj;
  GtkWidget *year_spin;
  GtkWidget *name_entry;
  GtkWidget *register_button;
  GtkWidget *combobox1;

  register_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (register_window), _("REGISTER"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (register_window), fixed1);

  day_spin_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  day_spin = gtk_spin_button_new (GTK_ADJUSTMENT (day_spin_adj), 1, 0);
  gtk_widget_show (day_spin);
  gtk_fixed_put (GTK_FIXED (fixed1), day_spin, 48, 144);
  gtk_widget_set_size_request (day_spin, 60, 27);

  month_spin_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  month_spin = gtk_spin_button_new (GTK_ADJUSTMENT (month_spin_adj), 1, 0);
  gtk_widget_show (month_spin);
  gtk_fixed_put (GTK_FIXED (fixed1), month_spin, 168, 144);
  gtk_widget_set_size_request (month_spin, 60, 27);

  year_spin_adj = gtk_adjustment_new (2022, 1950, 2022, 1, 10, 10);
  year_spin = gtk_spin_button_new (GTK_ADJUSTMENT (year_spin_adj), 1, 0);
  gtk_widget_show (year_spin);
  gtk_fixed_put (GTK_FIXED (fixed1), year_spin, 280, 144);
  gtk_widget_set_size_request (year_spin, 60, 27);

  name_entry = gtk_entry_new ();
  gtk_widget_show (name_entry);
  gtk_fixed_put (GTK_FIXED (fixed1), name_entry, 120, 64);
  gtk_widget_set_size_request (name_entry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (name_entry), 8226);

  register_button = gtk_button_new_with_mnemonic (_("REGISTER"));
  gtk_widget_show (register_button);
  gtk_fixed_put (GTK_FIXED (fixed1), register_button, 128, 248);
  gtk_widget_set_size_request (register_button, 136, 48);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), combobox1, 120, 192);
  gtk_widget_set_size_request (combobox1, 144, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("3Years"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("4Years"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("5Years"));

  g_signal_connect ((gpointer) register_button, "clicked",
                    G_CALLBACK (on_register_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (register_window, register_window, "register_window");
  GLADE_HOOKUP_OBJECT (register_window, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (register_window, day_spin, "day_spin");
  GLADE_HOOKUP_OBJECT (register_window, month_spin, "month_spin");
  GLADE_HOOKUP_OBJECT (register_window, year_spin, "year_spin");
  GLADE_HOOKUP_OBJECT (register_window, name_entry, "name_entry");
  GLADE_HOOKUP_OBJECT (register_window, register_button, "register_button");
  GLADE_HOOKUP_OBJECT (register_window, combobox1, "combobox1");

  return register_window;
}

