/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_inscription_window (void);
GtkWidget* create_authentification_window (void);
GtkWidget* create_espaceadmin_window (void);
