/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_inscription_window (void)
{
  GtkWidget *inscription_window;
  GtkWidget *fixed1;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkWidget *entry_username;
  GtkWidget *entry_password;
  GtkWidget *entry_role;
  GtkWidget *nom_label;
  GtkWidget *prenom_label;
  GtkWidget *username_label;
  GtkWidget *password_label;
  GtkWidget *role_label;
  GtkWidget *info_label;
  GtkWidget *inscription_label;
  GtkWidget *ajouter_bouton;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label7;
  GtkWidget *label_resultat;

  inscription_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (inscription_window, 400, 400);
  gtk_window_set_title (GTK_WINDOW (inscription_window), _("Inscription"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (inscription_window), fixed1);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_nom, 105, 80);
  gtk_widget_set_size_request (entry_nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_prenom, 105, 115);
  gtk_widget_set_size_request (entry_prenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_username = gtk_entry_new ();
  gtk_widget_show (entry_username);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_username, 105, 150);
  gtk_widget_set_size_request (entry_username, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_username), 8226);

  entry_password = gtk_entry_new ();
  gtk_widget_show (entry_password);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_password, 105, 185);
  gtk_widget_set_size_request (entry_password, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_password), 8226);

  entry_role = gtk_entry_new ();
  gtk_widget_show (entry_role);
  gtk_fixed_put (GTK_FIXED (fixed1), entry_role, 105, 220);
  gtk_widget_set_size_request (entry_role, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_role), 8226);

  nom_label = gtk_label_new (_("Nom:\t"));
  gtk_widget_show (nom_label);
  gtk_fixed_put (GTK_FIXED (fixed1), nom_label, 24, 88);
  gtk_widget_set_size_request (nom_label, 41, 17);

  prenom_label = gtk_label_new (_("Pr\303\251nom"));
  gtk_widget_show (prenom_label);
  gtk_fixed_put (GTK_FIXED (fixed1), prenom_label, 19, 120);
  gtk_widget_set_size_request (prenom_label, 64, 24);

  username_label = gtk_label_new (_("Username"));
  gtk_widget_show (username_label);
  gtk_fixed_put (GTK_FIXED (fixed1), username_label, 21, 152);
  gtk_widget_set_size_request (username_label, 72, 24);

  password_label = gtk_label_new (_("Password"));
  gtk_widget_show (password_label);
  gtk_fixed_put (GTK_FIXED (fixed1), password_label, 18, 188);
  gtk_widget_set_size_request (password_label, 80, 24);

  role_label = gtk_label_new (_("Role"));
  gtk_widget_show (role_label);
  gtk_fixed_put (GTK_FIXED (fixed1), role_label, 8, 216);
  gtk_widget_set_size_request (role_label, 64, 32);

  info_label = gtk_label_new (_("(1: Admin, 2:client,3:medecin)"));
  gtk_widget_show (info_label);
  gtk_fixed_put (GTK_FIXED (fixed1), info_label, 0, 248);
  gtk_widget_set_size_request (info_label, 256, 24);

  inscription_label = gtk_label_new (_("Inscription"));
  gtk_widget_show (inscription_label);
  gtk_fixed_put (GTK_FIXED (fixed1), inscription_label, 128, 24);
  gtk_widget_set_size_request (inscription_label, 136, 24);

  ajouter_bouton = gtk_button_new ();
  gtk_widget_show (ajouter_bouton);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter_bouton, 136, 296);
  gtk_widget_set_size_request (ajouter_bouton, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter_bouton), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox1), label7, FALSE, FALSE, 0);

  label_resultat = gtk_label_new ("");
  gtk_widget_show (label_resultat);
  gtk_fixed_put (GTK_FIXED (fixed1), label_resultat, 160, 352);
  gtk_widget_set_size_request (label_resultat, 49, 17);

  g_signal_connect ((gpointer) ajouter_bouton, "clicked",
                    G_CALLBACK (on_ajouter_bouton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscription_window, inscription_window, "inscription_window");
  GLADE_HOOKUP_OBJECT (inscription_window, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (inscription_window, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (inscription_window, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (inscription_window, entry_username, "entry_username");
  GLADE_HOOKUP_OBJECT (inscription_window, entry_password, "entry_password");
  GLADE_HOOKUP_OBJECT (inscription_window, entry_role, "entry_role");
  GLADE_HOOKUP_OBJECT (inscription_window, nom_label, "nom_label");
  GLADE_HOOKUP_OBJECT (inscription_window, prenom_label, "prenom_label");
  GLADE_HOOKUP_OBJECT (inscription_window, username_label, "username_label");
  GLADE_HOOKUP_OBJECT (inscription_window, password_label, "password_label");
  GLADE_HOOKUP_OBJECT (inscription_window, role_label, "role_label");
  GLADE_HOOKUP_OBJECT (inscription_window, info_label, "info_label");
  GLADE_HOOKUP_OBJECT (inscription_window, inscription_label, "inscription_label");
  GLADE_HOOKUP_OBJECT (inscription_window, ajouter_bouton, "ajouter_bouton");
  GLADE_HOOKUP_OBJECT (inscription_window, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (inscription_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (inscription_window, image1, "image1");
  GLADE_HOOKUP_OBJECT (inscription_window, label7, "label7");
  GLADE_HOOKUP_OBJECT (inscription_window, label_resultat, "label_resultat");

  return inscription_window;
}

GtkWidget*
create_authentification_window (void)
{
  GtkWidget *authentification_window;
  GtkWidget *fixed2;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *username_auth_label;
  GtkWidget *password_auth_label;
  GtkWidget *login_bouton;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;

  authentification_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (authentification_window, 391, 284);
  gtk_window_set_title (GTK_WINDOW (authentification_window), _("Authentification"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (authentification_window), fixed2);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed2), entry6, 128, 80);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed2), entry7, 128, 152);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  username_auth_label = gtk_label_new (_("Username"));
  gtk_widget_show (username_auth_label);
  gtk_fixed_put (GTK_FIXED (fixed2), username_auth_label, 32, 80);
  gtk_widget_set_size_request (username_auth_label, 88, 32);

  password_auth_label = gtk_label_new (_("Password"));
  gtk_widget_show (password_auth_label);
  gtk_fixed_put (GTK_FIXED (fixed2), password_auth_label, 40, 160);
  gtk_widget_set_size_request (password_auth_label, 49, 17);

  login_bouton = gtk_button_new ();
  gtk_widget_show (login_bouton);
  gtk_fixed_put (GTK_FIXED (fixed2), login_bouton, 136, 216);
  gtk_widget_set_size_request (login_bouton, 128, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (login_bouton), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Login"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) login_bouton, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification_window, authentification_window, "authentification_window");
  GLADE_HOOKUP_OBJECT (authentification_window, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (authentification_window, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (authentification_window, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (authentification_window, username_auth_label, "username_auth_label");
  GLADE_HOOKUP_OBJECT (authentification_window, password_auth_label, "password_auth_label");
  GLADE_HOOKUP_OBJECT (authentification_window, login_bouton, "login_bouton");
  GLADE_HOOKUP_OBJECT (authentification_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (authentification_window, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (authentification_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (authentification_window, label11, "label11");

  return authentification_window;
}

GtkWidget*
create_espaceadmin_window (void)
{
  GtkWidget *espaceadmin_window;
  GtkWidget *fixed3;
  GtkWidget *Espaceadmin_label;

  espaceadmin_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espaceadmin_window), _("Espace Administrateur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (espaceadmin_window), fixed3);

  Espaceadmin_label = gtk_label_new (_("Vous n'etes pas connect\303\251 "));
  gtk_widget_show (Espaceadmin_label);
  gtk_fixed_put (GTK_FIXED (fixed3), Espaceadmin_label, 40, 40);
  gtk_widget_set_size_request (Espaceadmin_label, 272, 112);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espaceadmin_window, espaceadmin_window, "espaceadmin_window");
  GLADE_HOOKUP_OBJECT (espaceadmin_window, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (espaceadmin_window, Espaceadmin_label, "Espaceadmin_label");

  return espaceadmin_window;
}

